### ISSUE TITLE
Character Models, Clipping, and Audio Issues

### ISSUE THREAD

**Issue by neurokinnetix** [ermaccer/MK160FPSPatch#1]
While on character select screen, some character models have rigging issues (character faces will not sit flush where they belong but will be stretched out). -- This is specifically noticeable for Kitana, Sindel, Kenshi, Nitara, Reiko, Baraka.

Causes clipping on some textures (such as on Subzero's, Scorpions, and Reptiles masks)

During fatalities/fatal blows the audio has some consistency issues (when the character screams, it sounds gargled and strange). 

Other than these bugs its amazing seeing these fatalities and final blows in 60 FPS

Will deal with the bugs until NRS decides to unlock the framecap natively.

Thanks for this awesome little mod :)

**Comment by RaffCode-Personal** [comment]
If those can not be fixed easily, I would love a version of the patch that allows to turn it off depending on the situation, for example in the menus (even though them at 60 is nice) and maybe the end of fight poses, to avoid the rigging issues.

IMO even with Sindel "long face" the advantage of 60 fps is way worth the glitches during fatalities and fatal blows.

**Comment by tutorialboss** [comment]
Would it be possible to have this fantastic mod change fps lock only for menus/invasions but not fatalities/fatal blows? or is it all or nothing? :)

**Comment by neurokinnetix** [comment]
I'm curious as to how this would effect online multiplayer. Has anybody tested this? Is this safe to run while playing against friends online?

**Comment by kgudgeirsson** [comment]
Unfortunately the character face models issue is a no go for me. If that can't be fixed, +1 to allowing it only in certain portions, like the menu.

**Comment by tutorialboss** [comment]
> Unfortunately the character face models issue is a no go for me. If that can't be fixed, +1 to allowing it only in certain portions, like the menu.

I'd be the happiest gamer if i could simply run around in the invasions maps in 60 fps - 30 feels like im running in slowmo

**Comment by ermaccer** [comment]
I'm slowly working on finding usual MK stuff, I have found info table again so I think I could detect gamemode and lock to invastions only, we'll see.

**Comment by kgudgeirsson** [comment]
Any plans to work on this further @ermaccer ?

**Comment by neurokinnetix** [comment]
Side note, I noticed that this patch also causes the story mode cut scenes to be capped to 60 fps... not a big deal, but I'd prefer those to be uncapped like they were initially.

**Comment by ermaccer** [comment]
https://github.com/ermaccer/MK160FPSPatch/releases/

Added an optional invasions only mode, set invasionsonly to true in the .ini file.

Also it seems that some skins now might have 60 FPS material already included, Van Damme's skin doesn't glitch out at all.

**Comment by daylightEX** [comment]
Is there a way to have the Invasions-only mode apply to that AND the menus? They're the only things I'd really use it for. Like, for everything that ISN'T cinematics?

**Comment by ermaccer** [comment]
Would probably need to add more filters to MKO functions that are executed, I added invasions mode because you don't really notice any visual glitches there that much.

**Comment by kgudgeirsson** [comment]
> https://github.com/ermaccer/MK160FPSPatch/releases/
> 
> Added an optional invasions only mode, set invasionsonly to true in the .ini file.
> 
> Also it seems that some skins now might have 60 FPS material already included, Van Damme's skin doesn't glitch out at all.

Thanks for doing this!

**Comment by Henrypham465** [comment]
hi wonder how can i install, is there any instructions?

**Comment by PcGod6969** [comment]
> hi wonder how can i install, is there any instructions?

"Extract mk160fps.zip to MK12\Binaries\Win64 folder of Mortal Kombat 1 (so that dsound.dll and dsound.ini ends up near SDL2.dll)."

**Comment by ermaccer** [comment]
As 60 FPS mode is now official, closing this & archiving the repo.
