### ISSUE TITLE
Setting InvasionsOnly=true causes the game to crash on launch. Version 1.1.1

### ISSUE THREAD

**Issue by SalemLockehart** [ermaccer/MK160FPSPatch#5]
I'm using the latest steam build of the game, listed as version [12711744 on steamdb](https://steamdb.info/app/1971870/patchnotes/), and [0.156-663440 in-game](https://images2.imgbox.com/57/85/HDABenM5_o.png).

The mod functions properly when InvasionsOnly is set to false.

Steps to recreate issue:

1. Place the dsound.dll and dsound.ini file into the steam directory here: C:\Games\Steam\steamapps\common\Mortal Kombat 1\MK12\Binaries\Win64
2. Open dsound.ini, and change InvasionsOnly=false into InvasionsOnly=true.
3. Attempt launching the game through Steam.

**Comment by ermaccer** [comment]
Fixed, kinda ignored the standalone version but this was working in the one with MK1Hook.
